apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-experiments
spec:
  selector:
    matchLabels:
      app: api-experiments
  template:
    metadata:
      labels:
        app: api-experiments
    spec:
      containers:
        - name: api-experiments
          image: jakwai01/api-experiments
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 10000

---
apiVersion: v1
kind: Service
metadata:
  name: api-experiments
spec:
  selector:
    app: api-experiments
  ports:
    - port: 10000
      targetPort: 10000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-experiments
spec:
  backend:
    serviceName: api-experiments
    servicePort: 10000
  rules:
    - host: api-experiments.services.jakobwaibel.com
      http:
        paths:
          - backend:
              serviceName: api-experiments
              servicePort: 10000
